export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';
export const CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST';
export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_DUPLICATE = 'CREATE_TOPIC_DUPLICATE';

export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';

export const INCREMENT_COUNT_REQUEST = 'INCREMENT_COUNT_REQUEST';
export const INCREMENT_COUNT_SUCCESS = 'INCREMENT_COUNT_SUCCESS';
export const INCREMENT_COUNT_FAILURE = 'INCREMENT_COUNT_FAILURE';

export const DECREMENT_COUNT_REQUEST = 'DECREMENT_COUNT_REQUEST';
export const DECREMENT_COUNT_SUCCESS = 'DECREMENT_COUNT_SUCCESS';
export const DECREMENT_COUNT_FAILURE = 'DECREMENT_COUNT_FAILURE';

export const DESTROY_TOPIC_REQUEST = 'DESTROY_TOPIC_REQUEST';
export const DESTROY_TOPIC_SUCCESS = 'DESTROY_TOPIC_SUCCESS';
export const DESTROY_TOPIC_FAILURE = 'DESTROY_TOPIC_FAILURE';

export const TYPING = 'TYPING';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';
