export const TYPING = 'TYPING';

export const GET_TOPICS = 'GET_TOPICS';
export const CREATE_TOPIC = 'CREATE_TOPIC';
export const DESTROY_TOPIC = 'DESTROY_TOPIC';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';

export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const DESTROY_TOPIC_SUCCESS = 'DESTROY_TOPIC_SUCCESS';
export const INCREMENT_COUNT_SUCCESS = 'INCREMENT_COUNT_SUCCESS';
export const DECREMENT_COUNT_SUCCESS = 'DECREMENT_COUNT_SUCCESS';
