export const TYPING = 'TYPING';

export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST';
export const DESTROY_TOPIC_REQUEST = 'DESTROY_TOPIC_REQUEST';
export const INCREMENT_COUNT_REQUEST = 'INCREMENT_COUNT_REQUEST';
export const DECREMENT_COUNT_REQUEST = 'DECREMENT_COUNT_REQUEST';

export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const DESTROY_TOPIC_SUCCESS = 'DESTROY_TOPIC_SUCCESS';
export const INCREMENT_COUNT_SUCCESS = 'INCREMENT_COUNT_SUCCESS';
export const DECREMENT_COUNT_SUCCESS = 'DECREMENT_COUNT_SUCCESS';
